name: Update Scoop Bucket
on:
  schedule:
    - cron: "*/30 * * * *"
  repository_dispatch:
    types: [aliae_release_published]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Update manifests
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
          INPUT_PROJECT: ${{ inputs.project }}
          INPUT_VERSION: ${{ inputs.version }}
        run: |
          ./scripts/update-manifests.ps1
